//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Retro_Achievement_Tracker.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Retro_Achievement_Tracker.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;title&gt;Notification Window&lt;/title&gt;
        ///    &lt;meta charset=&quot;UTF-8&quot;&gt;
        ///    &lt;script src=&quot;https://code.jquery.com/jquery-3.5.1.min.js&quot; type=&quot;text/javascript&quot;&gt;&lt;/script&gt;
        ///    &lt;script id=&quot;achievement-script&quot;&gt;
        ///
        ///        (async function () {
        ///            await CefSharp.BindObjectAsync(&quot;alertControllerAsync&quot;);
        ///        })();
        ///
        ///        function setPlayingOn() {
        ///            alertControllerAsync.setIsPlaying(true);
        ///        }
        ///
        ///        function setPlayingOff() {
        ///            alertCont [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AlertsWindow {
            get {
                return ResourceManager.GetString("AlertsWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;title&gt;Focus Window&lt;/title&gt;
        ///    &lt;meta charset=&quot;UTF-8&quot;&gt;
        ///    &lt;script src=&quot;https://code.jquery.com/jquery-3.5.1.min.js&quot; type=&quot;text/javascript&quot;&gt;&lt;/script&gt;
        ///    &lt;script id=&quot;focus-scripts&quot;&gt;
        ///        (function (root, factory) {
        ///            &quot;use strict&quot;;
        ///
        ///            // UMD shim
        ///            if (typeof define === &quot;function&quot; &amp;&amp; define.amd) {
        ///                // AMD
        ///                define([], factory);
        ///            } else if (typeof exports === &quot;object&quot;) {
        ///                // [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FocusWindow {
            get {
                return ResourceManager.GetString("FocusWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;title&gt;Game Info Window&lt;/title&gt;
        ///    &lt;meta charset=&quot;UTF-8&quot;&gt;
        ///    &lt;script src=&quot;https://code.jquery.com/jquery-3.5.1.min.js&quot; type=&quot;text/javascript&quot;&gt;&lt;/script&gt;
        ///    &lt;script id=&quot;scripts&quot;&gt;
        ///        (function (root, factory) {
        ///            &quot;use strict&quot;;
        ///
        ///            // UMD shim
        ///            if (typeof define === &quot;function&quot; &amp;&amp; define.amd) {
        ///                // AMD
        ///                define([], factory);
        ///            } else if (typeof exports === &quot;object&quot;) {
        ///                // N [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GameInfoWindow {
            get {
                return ResourceManager.GetString("GameInfoWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap green_button {
            get {
                object obj = ResourceManager.GetObject("green_button", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap green_button1 {
            get {
                object obj = ResourceManager.GetObject("green_button1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon image {
            get {
                object obj = ResourceManager.GetObject("image", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;title&gt;Last Five Window&lt;/title&gt;
        ///    &lt;meta charset=&quot;UTF-8&quot;&gt;
        ///    &lt;script src=&quot;https://code.jquery.com/jquery-3.5.1.min.js&quot; type=&quot;text/javascript&quot;&gt;&lt;/script&gt;
        ///    &lt;script id=&quot;last-five-scripts&quot;&gt;
        ///        function addToList(name, imageLink, description, points, date, id) {
        ///
        ///            var focusAchievementBlock = document.createElement(&apos;div&apos;);
        ///            focusAchievementBlock.classList.add(&quot;focus-achievement&quot;);
        ///            focusAchievementBlock.id = &quot;achievement-&quot; + id [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LastFiveWindow {
            get {
                return ResourceManager.GetString("LastFiveWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap notification_background {
            get {
                object obj = ResourceManager.GetObject("notification_background", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap red_button {
            get {
                object obj = ResourceManager.GetObject("red_button", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///    &lt;meta charset=&quot;UTF-8&quot;&gt;
        ///    &lt;script src=&quot;https://code.jquery.com/jquery-3.5.1.min.js&quot; type=&quot;text/javascript&quot;&gt;&lt;/script&gt;
        ///    &lt;script id=&quot;scripts&quot;&gt;
        ///        (function (root, factory) {
        ///            &quot;use strict&quot;;
        ///
        ///            // UMD shim
        ///            if (typeof define === &quot;function&quot; &amp;&amp; define.amd) {
        ///                // AMD
        ///                define([], factory);
        ///            } else if (typeof exports === &quot;object&quot;) {
        ///                // Node/CommonJS
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StatsWindow {
            get {
                return ResourceManager.GetString("StatsWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap yellow_button {
            get {
                object obj = ResourceManager.GetObject("yellow_button", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
