//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Retro_Achievement_Tracker.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.7.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ra_username {
            get {
                return ((string)(this["ra_username"]));
            }
            set {
                this["ra_username"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ra_key {
            get {
                return ((string)(this["ra_key"]));
            }
            set {
                this["ra_key"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool auto_start_checked {
            get {
                return ((bool)(this["auto_start_checked"]));
            }
            set {
                this["auto_start_checked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool auto_stats {
            get {
                return ((bool)(this["auto_stats"]));
            }
            set {
                this["auto_stats"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool auto_focus {
            get {
                return ((bool)(this["auto_focus"]));
            }
            set {
                this["auto_focus"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool auto_notifications {
            get {
                return ((bool)(this["auto_notifications"]));
            }
            set {
                this["auto_notifications"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#000000")]
        public string stats_font_color_hex_code {
            get {
                return ((string)(this["stats_font_color_hex_code"]));
            }
            set {
                this["stats_font_color_hex_code"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Calibri")]
        public string stats_font_family_name {
            get {
                return ((string)(this["stats_font_family_name"]));
            }
            set {
                this["stats_font_family_name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("52")]
        public float stats_font_size {
            get {
                return ((float)(this["stats_font_size"]));
            }
            set {
                this["stats_font_size"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool stats_font_outline_enabled {
            get {
                return ((bool)(this["stats_font_outline_enabled"]));
            }
            set {
                this["stats_font_outline_enabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFFFFF")]
        public string stats_font_outline_color_hex {
            get {
                return ((string)(this["stats_font_outline_color_hex"]));
            }
            set {
                this["stats_font_outline_color_hex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int stats_font_outline_size {
            get {
                return ((int)(this["stats_font_outline_size"]));
            }
            set {
                this["stats_font_outline_size"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#000000")]
        public string focus_font_color_hex_code {
            get {
                return ((string)(this["focus_font_color_hex_code"]));
            }
            set {
                this["focus_font_color_hex_code"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Calibri")]
        public string focus_font_family_name {
            get {
                return ((string)(this["focus_font_family_name"]));
            }
            set {
                this["focus_font_family_name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool focus_font_outline_enabled {
            get {
                return ((bool)(this["focus_font_outline_enabled"]));
            }
            set {
                this["focus_font_outline_enabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFFFFF")]
        public string focus_font_outline_color_hex {
            get {
                return ((string)(this["focus_font_outline_color_hex"]));
            }
            set {
                this["focus_font_outline_color_hex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int focus_font_outline_size {
            get {
                return ((int)(this["focus_font_outline_size"]));
            }
            set {
                this["focus_font_outline_size"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#CCCCCC")]
        public string focus_background_color {
            get {
                return ((string)(this["focus_background_color"]));
            }
            set {
                this["focus_background_color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#000000")]
        public string notification_font_color_hex_code {
            get {
                return ((string)(this["notification_font_color_hex_code"]));
            }
            set {
                this["notification_font_color_hex_code"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Calibri")]
        public string notification_font_family_name {
            get {
                return ((string)(this["notification_font_family_name"]));
            }
            set {
                this["notification_font_family_name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool notification_font_outline_enabled {
            get {
                return ((bool)(this["notification_font_outline_enabled"]));
            }
            set {
                this["notification_font_outline_enabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFFFFF")]
        public string notification_font_outline_color_hex {
            get {
                return ((string)(this["notification_font_outline_color_hex"]));
            }
            set {
                this["notification_font_outline_color_hex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int notification_font_outline_size {
            get {
                return ((int)(this["notification_font_outline_size"]));
            }
            set {
                this["notification_font_outline_size"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#CCCCCC")]
        public string notification_background_color {
            get {
                return ((string)(this["notification_background_color"]));
            }
            set {
                this["notification_background_color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool notification_custom_achievement_enable {
            get {
                return ((bool)(this["notification_custom_achievement_enable"]));
            }
            set {
                this["notification_custom_achievement_enable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool notification_custom_mastery_enable {
            get {
                return ((bool)(this["notification_custom_mastery_enable"]));
            }
            set {
                this["notification_custom_mastery_enable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string notification_custom_achievement_file {
            get {
                return ((string)(this["notification_custom_achievement_file"]));
            }
            set {
                this["notification_custom_achievement_file"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string notification_custom_mastery_file {
            get {
                return ((string)(this["notification_custom_mastery_file"]));
            }
            set {
                this["notification_custom_mastery_file"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-15")]
        public int notification_custom_achievement_x {
            get {
                return ((int)(this["notification_custom_achievement_x"]));
            }
            set {
                this["notification_custom_achievement_x"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int notification_custom_achievement_y {
            get {
                return ((int)(this["notification_custom_achievement_y"]));
            }
            set {
                this["notification_custom_achievement_y"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-15")]
        public int notification_custom_mastery_x {
            get {
                return ((int)(this["notification_custom_mastery_x"]));
            }
            set {
                this["notification_custom_mastery_x"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int notification_custom_mastery_y {
            get {
                return ((int)(this["notification_custom_mastery_y"]));
            }
            set {
                this["notification_custom_mastery_y"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.00")]
        public decimal notification_custom_achievement_scale {
            get {
                return ((decimal)(this["notification_custom_achievement_scale"]));
            }
            set {
                this["notification_custom_achievement_scale"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.00")]
        public decimal notification_custom_mastery_scale {
            get {
                return ((decimal)(this["notification_custom_mastery_scale"]));
            }
            set {
                this["notification_custom_mastery_scale"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300")]
        public int notification_custom_achievement_fade_in {
            get {
                return ((int)(this["notification_custom_achievement_fade_in"]));
            }
            set {
                this["notification_custom_achievement_fade_in"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300")]
        public int notification_custom_mastery_fade_in {
            get {
                return ((int)(this["notification_custom_mastery_fade_in"]));
            }
            set {
                this["notification_custom_mastery_fade_in"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300")]
        public int notification_custom_achievement_fade_out {
            get {
                return ((int)(this["notification_custom_achievement_fade_out"]));
            }
            set {
                this["notification_custom_achievement_fade_out"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300")]
        public int notification_custom_mastery_fade_out {
            get {
                return ((int)(this["notification_custom_mastery_fade_out"]));
            }
            set {
                this["notification_custom_mastery_fade_out"] = value;
            }
        }
    }
}
